[project]
name = "indexdb"
version = "0.1.0"
description = "INDEXDB"
readme = "README.md"
authors = [
    { name = "Shishir-Kc", email = "shishir.khatri.kc@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
indexdb = "src:main"
check = "src.dev_scripts.check:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "src"
module-root = ""

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]
